### ISSUE TITLE
StreamIds are not generated according to the spec

### ISSUE THREAD

**Issue by michaelbpaulson** [ReactiveSocket/reactivesocket-js#16]
https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md#stream-identifiers

Clients naively `++` a streamId value.

**Comment by yunong** [comment]
@michaelbpaulson has this been fixed?

**Comment by michaelbpaulson** [comment]
Yes, I believe so. I thought the last PR had this changes

**Comment by yunong** [comment]
Can we close this issue then?

**Comment by michaelbpaulson** [comment]
Not near computer, or else I would
