### ISSUE TITLE
Reserve package names and publish to npm

### ISSUE THREAD

**Issue by vjn** [ReactiveSocket/reactivesocket-js#29]
I noticed that this package isn't yet on npm. Ideally, both reactivesocket-js and reactivesocket should be reserved, to forestall user confusion.

(I work with Ben Christensen; at some point, we would need a lightweight version running on browsers, ideally w/o needing browserify. If nobody else is working on that, I could. Thanks!)

**Comment by yunong** [comment]
both packages have been reserved. @vjn happy to have you contribute. Right now the only hard requirement of this library is that the underlying transport is made available via the Node.js Stream API.
