### ISSUE TITLE
RS Connection Requires Bunyan Logger

### ISSUE THREAD

**Issue by kbahr** [ReactiveSocket/reactivesocket-js#39]
This is more a complaint/point for discussion than an issue per se - I don't like that I have to supply a Bunyan logger to create a connection. I would prefer that the library provide logging hooks if it wants to use Bunyan internally or make the logger that it will take more permissive (or at the very least, optional).

**Comment by micahr** [comment]
I might be wrong, but I think the logger option is optional: https://github.com/ReactiveSocket/reactivesocket-js/blob/master/lib/connection/connection.js#L42

**Comment by kbahr** [comment]
Thanks Micah - I had tested it incorrectly and thought that omitting a logger was causing a different failure. Given that, this issue can be closed :) Sorry to spam!
