### ISSUE TITLE
Be able to set a logger

### ISSUE THREAD

**Issue by michaelbpaulson** [ReactiveSocket/reactivesocket-js#4]
As of right now the logger is statically defined as the following:

``` javascript
var LOG = bunyan.createLogger({
    name: 'reactive-socket',
    level: 'error',
    src: true
});
```

It would be best if this logger was overridable.

**Comment by yunong** [comment]
The common pattern for this is for the library to take in a custom logger as part of an options object, which overrides the default.

Also, the default logger needs to turn off `src: true`, as this is not performant.

**Comment by yunong** [comment]
We'd prefer to create a new frame parser for each buffer, which encapsulates state for that particular frame.
