### ISSUE TITLE
Need to catch network error and retry for connection

### ISSUE THREAD

**Issue by leitsubomi** [ReactiveSocket/reactivesocket-js#40]
Here is the 2 type of error I observer
{msg=[Uncaught exception]: Got uncaught exception, nqGroup=akira_systems_test, err={"message":"write EPIPE","name":"Error","stack":"Error: write EPIPE\n    at exports._errnoException (util.js:870:11)\n    at WriteWrap.afterWrite (net.js:769:14)","code":"EPIPE"}, level=50, pid=430, rowId=d5cf39c8-8223-4370-bc20-267564b4b8b8, nqVersion=0.0.17, capp=nq_uiplatform_akira_systems_test, req_id=0e7acaac-cc54-4a31-995d-a271b54b7ace, hostname=titus-70914-worker-3-5, component=RESTServer, nqAccount=uiplatform, v=0, name=nodequark, time=2016-06-06T19:25:35.556Z, DB=node_quark}

{msg=[Uncaught exception]: Got uncaught exception, nqGroup=akira_systems_test, err={"message":"read ECONNRESET","name":"Error","stack":"Error: read ECONNRESET\n    at exports._errnoException (util.js:870:11)\n    at TCP.onread (net.js:552:26)","code":"ECONNRESET"}, level=50, pid=403, rowId=7d4c0e41-38c4-41ca-ac3b-85f01745df45, nqVersion=0.0.17, capp=nq_uiplatform_akira_systems_test, req_id=79379588-1bd2-4a47-84c2-d185df4e7515, hostname=titus-70914-worker-6-8, component=RESTServer, nqAccount=uiplatform, v=0, name=nodequark, time=2016-06-06T19:25:35.551Z, DB=node_quark}

**Comment by yunong** [comment]
fixed in e6947e6e385c5c811254ac00d2ddcad5f2e4bad3
