### ISSUE TITLE
Reactive Socket Metrics

### ISSUE THREAD

**Issue by yunong** [ReactiveSocket/reactivesocket-js#58]
Let's use this issue to classify the types of metrics we'd like to see this library collect and emit. 
Here are a few off the top of my head:

- Request/response latency
- Setup latency
- Timeout counts
- Various error counts

There will definitely be more for request response and other interactions.

**Comment by stevegury** [comment]
#59 is up for review.

**Comment by stevegury** [comment]
Closing per #59
