### ISSUE TITLE
RFC: Matching the latest spec & browser support

### ISSUE THREAD

**Issue by josephsavona** [ReactiveSocket/reactivesocket-js#66]
I'm opening this issue to start the discussion about how best to collaborate toward fully implementing the [latest spec proposal](https://github.com/ReactiveSocket/reactivesocket/blob/master/Protocol.md) and adding support for both Node and browsers. 

Some of the considerations from our (Facebook) perspective:

- Implementing the full specification (including eventually resumption) for the *client* side.
- Browser support using a variety of transports (Web Sockets, long-polling, etc). Ideally the architecture would support pluggable transports without relying on Node-only APIs (such as `Buffer`) or introducing extraneous data transformation (as could occur if the transport interface was strictly binary while some transports used ASCII/UTF).
- Minimizing code size. In particular the usage of third-party libraries such as lodash in the current version would create overlap with our internal library code (see [fbjs](https://github.com/facebook/fbjs)) and could substantially increase the final code size. Using internal libraries as much as possible would reduce code size for *us*, though we recognize that this is not a standard, documented library. Another consideration is which Rx library (if any) should be used for the public API methods that return multiple results over time (such as request/stream). A possible approach here is some form of dependency injection or shimming in the build process. 
- Static typing. We've found [Flow](https://flowtype.org/) to be useful in avoiding bugs, reducing the need for unit tests, and in avoiding the need for extensive (and possibly expensive) runtime assertions and checks as currently employed here. TypeScript is another option, though not well supported at Facebook.
- ES6 and Babel. I'm not sure how much newer language features are already being used, but it would be convenient to use them and we would then need Babel to produce the browser build. 

As a high-level approach, we could consider moving toward a mono-repo style, splitting the implementation into several npm packages all managed via this repository. A straw-man for this might include the following packages (named for example as `reactivesocket-*`):

- core
- client
- server
- Browser web socket transport
- Browser long-polling transport
- Node.js (HTTP) transport

With this approach, portions of the current codebase would move to either the "core" or the Node.js transport. Also, the client/server wrappers might also be a good place to combine the core with specific third-party Rx libraries (e.g. `reactivesocket-client-rxjs`). 

We are happy to take the lead in driving this effort and implementation (along the lines suggested above), but want to work with folks to find the best approach. Thoughts?

**Comment by josephsavona** [comment]
cc @stevegury

**Comment by josephsavona** [comment]
Edited to mention ES6/Babel and clarify that we are willing to drive this effort once consensus is reached on the approach.

**Comment by josephsavona** [comment]
Another consideration is that many of unimplemented interactions (request/stream, request/channel, etc) require an implementation of Reactive Streams, which [doesn't appear to exist in JavaScript yet](https://github.com/reactive-streams/reactive-streams-js). I'm experimenting with this now.

**Comment by yunong** [comment]
What do you mean by "reactive streams"? Are you referring to rxjs? The current node implementation is built on top of the node streams API, which supports back pressure out of the box, making it fairly trivial to implement the streaming interactions.

**Comment by yunong** [comment]
Here are some counter points to using flow, babel, or typescript. Specifically most of these implementations require a transpilation step. (Flow doesn't if you just use the annotations, but then you're not getting the full feature set). In general, transpilation makes debugging more difficult, especially on the server. Primarily this is because it's much harder to correlate and root cause server crashes back to their original source code. Core dumps and stack traces don't align back to the source code, making it difficult to debug problems in a production server environment.

**Comment by josephsavona** [comment]
@yunong Thanks for the feedback and questions.

> What do you mean by "reactive streams"?

I'm referring to the [Reactive Streams specification](What do you mean by "reactive streams"?), which provides an API *very* close to that of `rxjs` but not identical, as it provides for backpressure. I agree that it is likely possible to use a node streams implementation to implement that API, but that would have to be implemented.

> Here are some counter points to using flow, babel, or typescript.

Good points. I think we can find a middle ground here. For example, in order to eliminate the need to compile with babel when running in node on the server we can use only the new language features that are supported in some minimal node version (arrow functions are convenient). As for Flow, the npm package would export a version of the code in which all the type annotations are stripped but the code is otherwise unmodified and therefore should be easily readable/debuggable (unlike Typescript, which modifies code structure based on my understanding).

**Comment by stevegury** [comment]
> Implementing the full specification (including eventually resumption) for the client side.

👍
I think the best thing to do here is starting a long-lived branch `1.0` for that.
(We have running systems using the current version of the protocol)

> Browser support using a variety of transports (Web Sockets, long-polling, etc). Ideally the architecture would support pluggable transports without relying on Node-only APIs (such as Buffer) or introducing extraneous data transformation (as could occur if the transport interface was strictly binary while some transports used ASCII/UTF).

👍 

> Minimizing code size. In particular the usage of third-party libraries such as lodash in the current version would create overlap with our internal library code (see fbjs) and could substantially increase the final code size. Using internal libraries as much as possible would reduce code size for us, though we recognize that this is not a standard, documented library. Another consideration is which Rx library (if any) should be used for the public API methods that return multiple results over time (such as request/stream). A possible approach here is some form of dependency injection or shimming in the build process.

I would need to review the code to be sure, but I don't think we are heavily relying on lodash.

> Static typing. We've found Flow to be useful in avoiding bugs, reducing the need for unit tests, and in avoiding the need for extensive (and possibly expensive) runtime assertions and checks as currently employed here. TypeScript is another option, though not well supported at Facebook.

I agree with the value of types, I don't have experience with either TypeScript nor Flow. I think I've read that there may be ways to use Flow without transpilling the code, that would be ideal.

> ES6 and Babel. I'm not sure how much newer language features are already being used, but it would be convenient to use them and we would then need Babel to produce the browser build.

Migrating to ES6 is definitely something we need to do.
I've no experience with Babel, and if I understand correctly you want to use it to produce another lib just for the browser, right?

**Comment by josephsavona** [comment]
@stevegury Thanks for the feedback. Re usage of Flow/ES6, I imagine doing something like the following:
- Write all code using ES6 syntax such that it works without transpilation in [node >= 6.5](https://kangax.github.io/compat-table/es6/#node65)
- Use standard Flow declarations (e.g. `var x: number`, not the comment syntax). 
- Produce node-compatible builds (possibly as separate npm modules) that convert Flow declarations to comment syntax, such that when installed via npm the code not only works but is readable/debuggable (not munged beyond converting `var x: number` to `var x /*: number*/`).
- Produce browser-compatible builds that both transpile via Babel (which also strips Flow types).

I can also reach out to some folks with better npm-fu than me to set this up elegantly.

As far as next steps, how about I'll create a PR demonstrating some of the above so that we have concrete code to discuss?

**Comment by stevegury** [comment]
That next step sounds good to me, just start with a subset of the code, to demonstrate the feasibility. There's a bunch of dead code that I kept for backward compatibility, I will remove that before we work on the migration to rsocket 1.0 spec.

**Comment by josephsavona** [comment]
Let's continue discussion at #68. We're making progress on the new implementation and the new repo seems like a better place to publish that code.
